### ISSUE TITLE
Block Port 53 for all apps

### ISSUE THREAD

**Issue by tam481** [LayoutXML/SABS#12]
Hi @LayoutXML 
Blocking port 53 for Chrome only seems like a backwards step! Please re-enable blocking of port 53 for all apps. It is already a configurable option and people can choose to turn it on or off if they wish!

**Comment by eXPerience83** [comment]
I don't know why we need to block port 53 on other apps, and I think that if you block it on the settings it's for all the apps, not just Chrome. Isn't it?

**Comment by tam481** [comment]
It does at the moment, however, @LayoutXML's latest commit "https://github.com/LayoutXML/SABS/commit/50c33d577953bb4e17eddfb3418c8306f29cee21" changes that to Chrome only.

There are other apps that use their own dns servers which means they would be able to bypass SABS since they would be doing their own lookups.

**Comment by mmotti** [comment]
It is gross overkill at the moment to block all packages and causes more
problems than it's worth.

Chrome so far as been the only app that I've seen actively circumventing
blocking with the use of it's own DNS requests. I've personally not
experienced any other app displaying ads in this way.

On 21 Feb 2018 07:51, "tam481" <notifications@github.com> wrote:

It does at the moment, however, @LayoutXML <https://github.com/layoutxml>'s
latest commit "50c33d5
<https://github.com/LayoutXML/SABS/commit/50c33d577953bb4e17eddfb3418c8306f29cee21>"
changes that to Chrome only.

There are other apps that use their own dns servers which means they would
be able to bypass SABS since they would be doing their own lookups.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LayoutXML/SABS/issues/12#issuecomment-367240886>, or mute
the thread

**Comment by tam481** [comment]
Unfortunately, I have. The O2 Priority app does this as well. The best solution for everyone would be the ability to enable/disable blocking of port 53 on a per-app basis. I'm not sure how convoluted this might be to implement though.

**Comment by LayoutXML** [comment]
I hear you. Will make this an option.

**Comment by LayoutXML** [comment]
Added option to choose. Changes will be available on the next update.

**Comment by Mike-BITW** [comment]
**Tread carefully!**  Sooner or later someone will ask to have options to selectively block any port for any app. So far, the port 53 issue only seems to be relevant to a few Chrome versions (easily bypassed by setting the right chrome://flags) and to that "O2 App", maybe not enough to justify a lot of extra code and complexity  unless you implement a plugins system (blocker, disabler, permissions, DNS override, cosmetic filters, etc.). I've seen too many promising apps get bogged down into oblivion after trying to do too much for too many people.  Sometimes, saying NO is the wisest response! ;)
