### ISSUE TITLE
Can't uninstall duplicate SABS

### ISSUE THREAD

**Issue by Desert-Worms** [LayoutXML/SABS#49]
I installed SABS yesterday and came across the key verification error. So when I went through the steps to fix the problem and it worked. Only issue is that I now have SABS installed twice. One that is still asking to be authenticated and one that is "working". Under my application manager the Uninstall button is greyed out and there is no way to remove either of them. 

Also it doesn't seem like SABS is actually doing anything. (Even with port 53 for chrome)

**Comment by LayoutXML** [comment]
You have to remove administrator permissions from the copy of SABS you want to uninstall. You can do this in android settings or open the app you want to uninstall, press recent apps button on your navigation bar, press and hold app name, press on i (information) icon, click uninstall, deactivate and uninstall.
I'm closing the issue because it's not an actual issue with the app.
